<!DOCTYPE html>
<html lang="en">
<head>
    <title>Home</title>
    <meta charset="utf-8">
    <meta name="format-detection" content="telephone=no" />
    <link rel="icon" href="/template/images/favicon.ico">
    <link rel="shortcut icon" href="/template/images/favicon.ico" />
    <link rel="stylesheet" href="/template/css/style.css">
    <script src="/template/js/jquery.js"></script>
    <script src="/template/js/jquery-migrate-1.1.1.js"></script>
    <script src="/template/js/jquery.easing.1.3.js"></script>
    <script src="/template/js/script.js"></script>
    <script src="/template/js/superfish.js"></script>
    <script src="/template/js/jquery.equalheights.js"></script>
    <script src="/template/js/jquery.mobilemenu.js"></script>
    <script src="/template/js/tmStickUp.js"></script>
    <script src="/template/js/jquery.ui.totop.js"></script>
    <script>
        $(window).load(function(){
            $().UItoTop({ easingType: 'easeOutQuart' });
            $('#stuck_container').tmStickUp({});
        });
    </script>
    <!--[if lt IE 8]>
    <div style=' clear: both; text-align:center; position: relative;'>
        <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
            <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
        </a>
    </div>
    <![endif]-->
    <!--[if lt IE 9]>
    <script src="/template/js/html5shiv.js"></script>
    <link rel="stylesheet" media="screen" href="/template/css/ie.css">
    <![endif]-->
</head>
<body class="page1" id="top">
<!--==============================
              header
=================================-->
<header>
    <div class="container">
        <div class="row">
            <div class="grid_12 rel">
                <h1>
                    <a href="index.html">
                        <img src="/template/images/logo.png" alt="Logo alt">
                    </a>
                </h1>
            </div>
        </div>
    </div>
    <section id="stuck_container">
        <!--==============================
                    Stuck menu
        =================================-->
        <div class="container">
            <div class="row">
                <div class="grid_12 ">
                    <div class="navigation ">
                        <nav>
                            <ul class="sf-menu">
                                <li class="current"><a href="index">Головна сторінка</a></li>
                                <li><a href="about">Про компанію</a></li>
                                <li><a href="services">Наші послуги</a></li>
                                <li><a href="blog">Блог</a></li>
                                <li><a href="contacts">Контакти</a></li>
                            </ul>
                        </nav>
                        <div class="clear"></div>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </section>
    <section class="page1_header">
        <div class="container">
            <div class="row">
                <div class="grid_4">
                    <a href="#" class="banner "><div class="maxheight">
                            <div class="fa fa-globe"></div>Global Research</div>
                    </a>
                    <a href="#" class="banner "><div class="maxheight">
                            <div class="fa fa-lightbulb-o"></div>Creative Ideas</div>
                    </a>
                    <a href="#" class="banner "><div class="maxheight1">
                            <div class="fa fa-cog"></div>New Services</div>
                    </a>
                    <a href="#" class="banner "><div class="maxheight1">
                            <div class="fa fa-briefcase"></div>Pro Management</div>
                    </a>
                </div>
                <div class="grid_5">
                    <h2>Кращі рішення <br> Стабільність <br> Безпека</h2>
                    Ми зробимо ваш бізнес успішним
                </div>
            </div>
        </div>
    </section>
</header>
<div class="block-1">
    <div class="container">
        <div class="row">
            <div class="grid_3">
                <div class="block-1_count">30</div>
                Років <br> досвіду
                <div class="clear"></div>
            </div>
            <div class="grid_3">
                <div class="block-1_count">300</div>
                Успішних <br> проєктів
                <div class="clear"></div>
            </div>
            <div class="grid_3">
                <div class="block-1_count">20</div>
                Партнерських <br> проєктів
                <div class="clear"></div>
            </div>
            <div class="grid_3">
                <a href="#" class="support"><img src="/template/images/support.png" alt=""></a>
            </div>
        </div>
    </div>
</div>
<!--=====================
          Content
======================-->
<section id="content"><div class="ic">More Website Templates @ TemplateMonster.com - July 28, 2014!</div>
    <div class="container">
        <div class="row">
            <div class="grid_10 preffix_1 ta__center">
                <div class="greet">
                    <h2 class="head__1">
                        IT-Enterprise
                    </h2>
                    <p>Компанія IT-Enterprise понад 30 років в займається впровадженням ІТ-рішень для автоматизації бізнес-процесів на підприємствах різних напрямів діяльності і має значний досвід розробок і впровадження найскладніших ERP-систем. <br> </p>
                    На базі досвіду розробок і впровадження кращих рішень IT-Enterprise на підприємствах-флагманах українського бізнесу створені програмні продукти MASTER для підприємств малого та середнього бізнесу та бюджетних установ України.
                </div>
            </div>
        </div>
    </div>
    <article class="content_gray">
        <div class="container">
            <div class="row">
                <div class="grid_7">
                    <h3>Наші переваги</h3>
                    <?foreach ($this->topNews as $news):?>
                    <div class="block-2">
                        <img src="/template/images/page1_img1.jpg" alt="" class="img_inner fleft">
                        <div class="extra_wrapper">
                            <div class="text1"><a href="#"><?=$news['news_title']?></a></div>
                            <p><?=$news['news_short_content']?></p>
                            <br>
                            <a href="#" class="link-1">Детальніше...</a>
                        </div>
                    </div>
                    <?endforeach;?>

                </div>
                <div class="grid_4 preffix_1">
                    <h3>Відгуки клієнтів</h3>
                    <?foreach ($this->commentNews as $comment):?>
                    <blockquote class="bq1">
                        <p>“<?=$comment['comment_text']?>”</p>
                        <p><h6><? $new_datetime = DateTime::createFromFormat ( "Y-m-d H:i:s", $comment['comment_date']);
                            echo $new_datetime->format('d - m - Y') ?></h6>
                        <span><?=$comment['user_name']?></span>
                    </blockquote>
                    <?endforeach;?>

                </div>
            </div>
        </div>
    </article>
    <div class="container">
        <div class="row">
            <div class="grid_5">
                <h4>About Company</h4>
                <img src="/template/images/page1_img3.jpg" alt="" class="img_inner fleft">
                <p>Curabitur vel lorem sit amet nulla ullamcorper fermentum In vitae dert arius augue, eu consectetur </p>
                <p class="offset__1">Eligulaam dui eros dertolisce dertolo adipiscing quam id risus sagittis</p>
                Curabitur vel lorem sit amet nulla ullamcorper fermentum In vitae dert rius augue, eu consectetur larem dui eros dertolisce dertolo
            </div>
            <div class="grid_4">
                <h4>Solutions</h4>
                <ul class="list-1">
                    <li><a href="#">Vivamus at magna non nunc tristique </a></li>
                    <li><a href="#">Aliquam nibh ante, egestas id</a></li>
                    <li><a href="#">Ommodo luctus libero</a></li>
                    <li><a href="#">Faucibus malesuada faucibusonec </a></li>
                    <li><a href="#">Laoreet metus id laoreet</a></li>
                    <li><a href="#">Jalesuadaorem ipsum dolor sit ame</a></li>
                </ul>
            </div>
            <div class="grid_3">
                <h4>Contact Info</h4>
                <address>
                    <ul class="cont_address">
                        <li>8901 Marmora Road, Glasgow, D04 89GR</li>
                        <li>+1 (800) 123 9876</li>
                        <li><a href="#">info@demolink.org</a></li>
                        <li><a href="#">www.demolink.org</a></li>
                    </ul>
                </address>
            </div>
        </div>
    </div>
</section>
<!--==============================
              footer
=================================-->
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="grid_12">
                <div class="copyright"><span class="brand">Stable</span> &copy; <span id="copyright-year"></span> | <a href="#">Privacy Policy</a>
                    <div class="sub-copy">Website designed by <a href="http://www.templatemonster.com/" rel="nofollow">TemplateMonster.com</a></div>
                </div>
            </div>
        </div>
    </div>
</footer>
<a href="#" id="toTop" class="fa fa-chevron-up"></a>
</body>
</html>