<!DOCTYPE html>
<html lang="en">
<head>
    <title>Blog</title>
    <meta charset="utf-8">
    <meta name="format-detection" content="telephone=no" />
    <link rel="icon" href="/template/images/favicon.ico">
    <link rel="shortcut icon" href="/template/images/favicon.ico" />
    <link rel="stylesheet" href="/template/css/style.css">
    <script src="/template/js/jquery.js"></script>
    <script src="/template/js/jquery-migrate-1.1.1.js"></script>
    <script src="/template/js/jquery.easing.1.3.js"></script>
    <script src="/template/js/script.js"></script>
    <script src="/template/js/superfish.js"></script>
    <script src="/template/js/jquery.equalheights.js"></script>
    <script src="/template/js/jquery.mobilemenu.js"></script>
    <script src="/template/js/tmStickUp.js"></script>
    <script src="/template/js/jquery.ui.totop.js"></script>
    <script>
        $(window).load(function(){
            $().UItoTop({ easingType: 'easeOutQuart' });
            $('#stuck_container').tmStickUp({});
        });
    </script>
    <!--[if lt IE 8]>
    <div style=' clear: both; text-align:center; position: relative;'>
        <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
            <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
        </a>
    </div>
    <![endif]-->
    <!--[if lt IE 9]>
    <script src="/template/js/html5shiv.js"></script>
    <link rel="stylesheet" media="screen" href="/template/css/ie.css">
    <![endif]-->
</head>
<body>
<!--==============================
              header
=================================-->
<header>
    <div class="container">
        <div class="row">
            <div class="grid_12 rel">
                <h1>
                    <a href="index.html">
                        <img src="/template/images/logo.png" alt="Logo alt">
                    </a>
                </h1>
            </div>
        </div>
    </div>
    <section id="stuck_container">
        <!--==============================
                    Stuck menu
        =================================-->
        <div class="container">
            <div class="row">
                <div class="grid_12 ">
                    <div class="navigation ">
                        <nav>
                            <ul class="sf-menu">
                                <li><a href="index">Головна сторінка</a></li>
                                <li><a href="about">Про компанію</a></li>
                                <li><a href="services">Наші послуги</a></li>
                                <li class="current"><a href="blog">Блог</a></li>
                                <li><a href="contacts">Контакти</a></li>
                            </ul>
                        </nav>
                        <div class="clear"></div>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </section>
</header>
<!--=====================
          Content
======================-->
<section id="content"><div class="ic">More Website Templates @ TemplateMonster.com - July 28, 2014!</div>
    <div class="container">
        <div class="row">
            <div class="grid_12">
                <h3>Наш блог</h3>
                <?foreach ($this->blogGet as $blogs):?>
                <div class="blog">
                    <time datetime="2014-01-01"><span class="count">2</span><strong>July</strong>2014</time>
                    <img src="<?=$blogs['photo']?>" alt="" class="img_inner fleft">
                    <div class="extra_wrapper">
                        <a href="#" class="comment"><span class="fa fa-comments"></span> <?=$blogs['comment_number']?></a>
                        <p><span class="fwn"><a href="#"><?=$blogs['title']?></a></span><em>Posted by: <a href="#"><?=$blogs['author']?></a></em></p><?=$blogs['text']?>
                        <br>
                        <a href="detail/<?= $blogs['id']?>/" class="link-1">детальніше...</a>
                    </div>
                </div>
                <?endforeach;?>

            </div>
        </div>
    </div>
</section>
<!--==============================
              footer
=================================-->
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="grid_12">
                <div class="copyright"><span class="brand">Stable</span> &copy; <span id="copyright-year"></span> | <a href="#">Privacy Policy</a>
                    <div class="sub-copy">Website designed by <a href="http://www.templatemonster.com/" rel="nofollow">TemplateMonster.com</a></div>
                </div>
            </div>
        </div>
    </div>
</footer>
<a href="#" id="toTop" class="fa fa-chevron-up"></a>
</body>
</html>