<!DOCTYPE html>
<html lang="en">
<head>
    <title>Наші контакти</title>
    <meta charset="utf-8">
    <meta name="format-detection" content="telephone=no" />
    <link rel="icon" href="/template/images/favicon.ico">
    <link rel="shortcut icon" href="/template/images/favicon.ico" />
    <link rel="stylesheet" href="/template/css/contact-form.css">
    <link rel="stylesheet" href="/template/css/style.css">
    <script src="/template/js/jquery.js"></script>
    <script src="/template/js/jquery-migrate-1.1.1.js"></script>
    <script src="/template/js/jquery.easing.1.3.js"></script>
    <script src="/template/js/script.js"></script>
    <script src="/template/js/superfish.js"></script>
    <script src="/template/js/jquery.equalheights.js"></script>
    <script src="/template/js/jquery.mobilemenu.js"></script>
    <script src="/template/js/tmStickUp.js"></script>
    <script src="/template/js/jquery.ui.totop.js"></script>
    <script src="/template/js/TMForm.js"></script>
    <script src="/template/js/modal.js"></script>
    <script>
        $(window).load(function(){
            $().UItoTop({ easingType: 'easeOutQuart' });
            $('#stuck_container').tmStickUp({});
        });
    </script>
    <!--[if lt IE 8]>
    <div style=' clear: both; text-align:center; position: relative;'>
        <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
            <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
        </a>
    </div>
    <![endif]-->
    <!--[if lt IE 9]>
    <script src="/template/js/html5shiv.js"></script>
    <link rel="stylesheet" media="screen" href="/template/css/ie.css">
    <![endif]-->
</head>
<body>
<!--==============================
              header
=================================-->
<header>
    <div class="container">
        <div class="row">
            <div class="grid_12 rel">
                <h1>
                    <a href="/index">
                        <img src="/template/images/logo.png" alt="Logo alt">
                    </a>
                </h1>
            </div>
        </div>
    </div>
    <section id="stuck_container">
        <!--==============================
                    Stuck menu
        =================================-->
        <div class="container">
            <div class="row">
                <div class="grid_12 ">
                    <div class="navigation ">
                        <nav>
                            <ul class="sf-menu">
                                <li><a href="/index">Головна сторінка</a></li>
                                <li><a href="/about">Про компанію</a></li>
                                <li><a href="/services">Наші послуги</a></li>
                                <li><a href="/blog">Блог</a></li>
                                <li class="current"><a href="/contacts">Контакти</a></li>
                            </ul>
                        </nav>
                        <div class="clear"></div>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </section>
</header>
<!--=====================
          Content
======================-->
<section id="content"><div class="ic">More Website Templates @ TemplateMonster.com - July 28, 2014!</div>
    <div class="container">
        <div class="row">
            <div class="grid_12">
                <h3>Наші контакти:</h3>
                <div class="map">
                    <figure class="">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d24214.807650104907!2d-73.94846048422478!3d40.65521573400813!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sus!4v1395650655094" style="border:0"></iframe>
                    </figure>
                </div>
            </div>
            <div class="grid_5">
                <h3 class="head__1">Адреса:</h3>
                <address class="text3">
                    138 Atlantis Ln <br>Kingsport <br>Illinois121164
                </address>
            </div>
            <div class="grid_4">
                <h3 class="head__1">Phone:</h3>
                <div class="text3">
                    +1 800 559 6580 <br>+1 504 889 9898
                </div>
            </div>
            <div class="grid_3">
                <h3 class="head__1">E-mail:</h3>
                <div class="text3">
                    <a href="#">mail@demolink.org</a><br><a href="#">Download</a>
                </div>
            </div>
            <div class="grid_12">
                <h3 class="head__1">Miscellaneous information:</h3>
                <div class="fwn">
                    <p>24/7 support is available for all <a href="http://www.templatemonster.com/" rel="nofollow" class="color1">premium themes</a>.</p>
                    <p>If you have problems with customization of freebies, ask guys from <a href="http://www.templatetuning.com/" rel="nofollow" class="color1">TemplateTuning</a> to help you.</p>
                    Aliquam nibh ante, egestas id dictum a, commodo luctus liberoret. Praesenter faucibus malesuada faucibus. Donec laoreet metus id laoreet malesuada. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam consectetur orci sed nulla facilisis consequa.
                </div>
            <form name="add post" method="post" action="/blog"
            <fieldset>

                <label class="name">
                    <input type="text" name="author" placeholder="Автор:">
                </label>

                <label class="email">
                    <input type="email" name="email" placeholder="Email:">
                </label>

                <label class="message">
                    <input type="text" name="text" placeholder="Введите текст" size="100">
                </label>

            </fieldset>
                <input type="submit" name="submit" value="Готово">
            </form>

            </div>
        </div>
    </div>
</section>
<!--==============================
              footer
=================================-->
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="grid_12">
                <div class="copyright"><span class="brand">Stable</span> &copy; <span id="copyright-year"></span> | <a href="#">Privacy Policy</a>
                    <div class="sub-copy">Website designed by <a href="http://www.templatemonster.com/" rel="nofollow">TemplateMonster.com</a></div>
                </div>
            </div>
        </div>
    </div>
</footer>
<a href="#" id="toTop" class="fa fa-chevron-up"></a>
</body>
</html>